---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.strategy }}
  strategy:
{{ toYaml .Values.strategy | indent 10 }}
  {{- end }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- include "traefik-forward-auth.pod.annotations" . | nindent 8 }}
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "traefik-forward-auth.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: proxy
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        {{- if .Values.pod.env }}
        env:
{{ toYaml .Values.pod.env | indent 10 }}
        {{- end }}
        {{- if .Values.command }}
        command:
{{ toYaml .Values.command | indent 10 }}
        {{- end }}
        {{- if .Values.args }}
        args:
{{ toYaml .Values.args | indent 10 }}
        {{- end }}
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
        - containerPort: 4181
        volumeMounts:
          - name: config
            mountPath: "/config"
          {{- if .Values.pod.volumeMounts }}
{{ toYaml .Values.pod.volumeMounts | indent 10 }}
          {{- end }}
        {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        {{- end }}
        {{- if .Values.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        {{- end }}
        {{- if .Values.startupProbe }}
        startupProbe:
{{ toYaml .Values.startupProbe | indent 10 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}-config
          items:
          - key: config.ini
            path: "config.ini"
      {{- if .Values.pod.volumes }}
{{ toYaml .Values.pod.volumes | indent 6 }}
      {{- end }}
---
